#配置端口
server:
  port: 80
#配置数据源的属性
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://你的IP:3306/ms?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=UTC&nullCatalogMeansCurrent=true
      username: root
      password: root
      max-active: 100
      max-wait: 5000
      initial-size: 1
      filters: stat,log4j,wall
      validationQuery: SELECT 'x'   #验证连接
      enable: true
      #监控配置
      stat-view-servlet:
        enabled: true
        login-username: root
        login-password: root
        allow:
        deny:
        url-pattern: /druid/*
      test-on-borrow: true
      test-while-idle: true
  #thymeleaf的配置
  thymeleaf:
    cache: false
    enabled: true
  #      web-stat-filter:
  #        enabled: true
  #        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
#  aop:
#    proxy-target-class: true
#配置mybatisplus
mybatis-plus:
  mapper-locations:
  - classpath:mapper/*.xml
  global-config:
    db-config:
      id-type: auto
    banner: true
    #  configuration:
    #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#shiro的配置
shiro:
  hash-algorithm-name: md5
  hash-iterations: 2
  anon-urls:
  - /index.html*
  - /sys/toLogin*
  - /login/login*
  - /resources/**
  login-url: /index.html
  log-out-url: /login/logout*
  authc-ulrs:
  - /**

